<?php

namespace App\Services;

/**
 * Canonical system menu definitions synced by modules:sync-menus.
 */
class ModuleMenuCatalog
{
    public const HR_SETTINGS_PERMISSION = 'view-hr-settings|view-vacancies|view-job-title|view-department|view-worksite|view-holidays|view-relationship|view-degree|view-country|view-district|view-locality|view-institution';

    public static function definitions(): array
    {
        return [
            [
                'system_key' => 'payroll.dashboard',
                'module_code' => 'payroll',
                'title' => 'Dashboard',
                'route' => '/',
                'icon' => 'dashboard',
                'permission' => 'view-dashboard',
                'order' => 1,
                'type' => 'menu',
            ],
            [
                'system_key' => 'payroll.reports',
                'module_code' => 'payroll',
                'title' => 'Reports',
                'route' => '/payroll/reports',
                'icon' => 'assessment',
                'permission' => 'view-reports',
                'order' => 8,
                'type' => 'menu',
            ],
            [
                'system_key' => 'employee.dashboard',
                'module_code' => 'employee',
                'title' => 'Dashboard',
                'route' => '/employee',
                'icon' => 'dashboard',
                'permission' => null,
                'order' => 1,
                'type' => 'menu',
            ],
            [
                'system_key' => 'employee.scheduler',
                'module_code' => 'employee',
                'title' => 'Scheduler',
                'route' => '/payroll/scheduler',
                'icon' => 'calendar_month',
                'permission' => 'view-calendars',
                'order' => 2,
                'type' => 'menu',
            ],
            [
                'system_key' => 'hr.employees',
                'module_code' => 'hr',
                'title' => 'Employees',
                'route' => '/hr/employees',
                'icon' => 'groups',
                'permission' => 'view-employees',
                'order' => 2,
                'type' => 'menu',
            ],
            [
                'system_key' => 'hr.vacancies',
                'module_code' => 'hr',
                'title' => 'Vacancies',
                'route' => '/hr/vacancies',
                'icon' => 'work',
                'permission' => 'view-vacancies',
                'order' => 3,
                'type' => 'menu',
            ],
            [
                'system_key' => 'hr.candidates',
                'module_code' => 'hr',
                'title' => 'Candidates',
                'route' => '/hr/candidates',
                'icon' => 'badge',
                'permission' => 'view-vacancies',
                'order' => 4,
                'type' => 'menu',
            ],
            [
                'system_key' => 'hr.settings',
                'module_code' => 'hr',
                'title' => 'Settings',
                'route' => '/hr/settings',
                'icon' => 'settings',
                'permission' => self::HR_SETTINGS_PERMISSION,
                'order' => 5,
                'type' => 'menu',
            ],
            [
                'system_key' => 'hr.settings.vacancy_stages',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Vacancy pipeline',
                'route' => '/hr/settings/vacancy-stages',
                'icon' => 'view_kanban',
                'permission' => 'view-vacancies',
                'order' => 1,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.candidate_stages',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Candidate pipeline',
                'route' => '/hr/settings/candidate-stages',
                'icon' => 'account_tree',
                'permission' => 'view-vacancies',
                'order' => 2,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.job_titles',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Job Titles',
                'route' => '/hr/settings/job-titles',
                'icon' => 'work',
                'permission' => 'view-job-title',
                'order' => 3,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.department',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Department',
                'route' => '/hr/settings/department',
                'icon' => 'fas fa-sitemap',
                'permission' => 'view-department',
                'order' => 4,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.worksite',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Work Site',
                'route' => '/hr/settings/worksite',
                'icon' => 'fas fa-map',
                'permission' => 'view-worksite',
                'order' => 5,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.holidays',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Public Holidays',
                'route' => '/hr/settings/holidays',
                'icon' => 'event',
                'permission' => 'view-holidays',
                'order' => 6,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.relationship',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Relationship',
                'route' => '/hr/settings/relationship',
                'icon' => 'fas fa-users',
                'permission' => 'view-relationship',
                'order' => 7,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.degree',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Degree',
                'route' => '/hr/settings/degree',
                'icon' => 'fas fa-graduation-cap',
                'permission' => 'view-degree',
                'order' => 8,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.country',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Country',
                'route' => '/hr/settings/country',
                'icon' => 'fas fa-globe',
                'permission' => 'view-country',
                'order' => 9,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.district',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'District',
                'route' => '/hr/settings/district',
                'icon' => 'fas fa-map-marker-alt',
                'permission' => 'view-district',
                'order' => 10,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.locality',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Locality',
                'route' => '/hr/settings/locality',
                'icon' => 'fas fa-map-pin',
                'permission' => 'view-locality',
                'order' => 11,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.institution',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Institution',
                'route' => '/hr/settings/institution',
                'icon' => 'fas fa-university',
                'permission' => 'view-institution',
                'order' => 12,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.birthdays',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Birthdays',
                'route' => '/hr/settings/birthdays',
                'icon' => 'cake',
                'permission' => self::HR_SETTINGS_PERMISSION,
                'order' => 13,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.letter_templates',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Letter templates',
                'route' => '/hr/settings/letter-templates',
                'icon' => 'description',
                'permission' => self::HR_SETTINGS_PERMISSION,
                'order' => 14,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'hr.settings.email_templates',
                'module_code' => 'hr',
                'parent_system_key' => 'hr.settings',
                'title' => 'Email templates',
                'route' => '/hr/settings/email-templates',
                'icon' => 'email',
                'permission' => self::HR_SETTINGS_PERMISSION,
                'order' => 15,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'payroll.employees',
                'module_code' => 'payroll',
                'title' => 'Employees',
                'route' => '/payroll/employees',
                'icon' => 'groups',
                'permission' => 'view-employees',
                'order' => 2,
                'type' => 'menu',
            ],
            [
                'system_key' => 'hr.scheduler',
                'module_code' => 'payroll',
                'title' => 'Scheduler',
                'route' => '/payroll/scheduler',
                'icon' => 'calendar_month',
                'permission' => 'view-calendars',
                'order' => 3,
                'type' => 'menu',
            ],
            [
                'system_key' => 'hr.timesheet',
                'module_code' => 'payroll',
                'title' => 'Timesheet',
                'route' => '/payroll/timesheet',
                'icon' => 'schedule',
                'permission' => 'view-timesheets',
                'order' => 4,
                'type' => 'menu',
            ],
            [
                'system_key' => 'hr.leaves',
                'module_code' => 'payroll',
                'title' => 'Leaves',
                'route' => '/payroll/leaves',
                'icon' => 'event_busy',
                'permission' => 'view-leave',
                'order' => 5,
                'type' => 'menu',
            ],
            [
                'system_key' => 'payroll.root',
                'module_code' => 'payroll',
                'title' => 'Payroll',
                'route' => '/payroll',
                'icon' => 'payments',
                'permission' => 'view-payroll',
                'order' => 6,
                'type' => 'menu',
            ],
            [
                'system_key' => 'payroll.settings',
                'module_code' => 'payroll',
                'title' => 'Settings',
                'route' => '/payroll/settings',
                'icon' => 'settings',
                'permission' => 'view-settings',
                'order' => 7,
                'type' => 'menu',
            ],
            [
                'system_key' => 'admin.settings',
                'module_code' => 'admin',
                'title' => 'Settings',
                'route' => '/admin/settings',
                'icon' => 'settings',
                'permission' => 'view-settings',
                'order' => 1,
                'type' => 'menu',
            ],
            [
                'system_key' => 'admin.pipelines',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Pipelines',
                'route' => '/admin/settings/pipelines',
                'icon' => 'account_tree',
                'permission' => 'view-pipeline-templates',
                'order' => 1,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.modules',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Modules',
                'route' => '/admin/settings/modules',
                'icon' => 'apps',
                'permission' => 'manage-modules',
                'order' => 2,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.database_backup',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Database Backup',
                'route' => '/admin/settings/database-backup',
                'icon' => 'fas fa-database',
                'permission' => 'view-database-backup',
                'order' => 3,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.file_storage',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'File Storage',
                'route' => '/admin/settings/file-storage',
                'icon' => 'cloud',
                'permission' => 'view-file-storage',
                'order' => 8,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.email',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Email',
                'route' => '/admin/settings/email',
                'icon' => 'email',
                'permission' => 'view-email-settings',
                'order' => 11,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.login',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Login',
                'route' => '/admin/settings/login',
                'icon' => 'lock',
                'permission' => 'manager-users',
                'order' => 9,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.login_page',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Login Page',
                'route' => '/admin/settings/login-page',
                'icon' => 'view_quilt',
                'permission' => 'view-login-page',
                'order' => 10,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.menu',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Menu',
                'route' => '/admin/settings/menu',
                'icon' => 'fas fa-bars',
                'permission' => 'view-menu',
                'order' => 4,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.roles',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Roles',
                'route' => '/admin/settings/roles',
                'icon' => 'fas fa-user-shield',
                'permission' => 'view-roles',
                'order' => 5,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.organization',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Organization',
                'route' => '/admin/settings/organization',
                'icon' => 'fas fa-building',
                'permission' => 'view-organization',
                'order' => 6,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.users',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Users',
                'route' => '/admin/settings/users',
                'icon' => 'fa-solid fa-users',
                'permission' => 'manager-users|reset-subordinate-passwords',
                'order' => 7,
                'type' => 'submenu',
            ],
        ];
    }
}
