<?php

namespace App\Services;

/**
 * Canonical system menu definitions synced by modules:sync-menus.
 */
class ModuleMenuCatalog
{
    public static function definitions(): array
    {
        return [
            [
                'system_key' => 'core.dashboard',
                'module_code' => 'payroll',
                'title' => 'Dashboard',
                'route' => '/',
                'icon' => 'dashboard',
                'permission' => 'view-dashboard',
                'order' => 1,
                'type' => 'menu',
            ],
            [
                'system_key' => 'core.reports',
                'module_code' => 'payroll',
                'title' => 'Reports',
                'route' => '/payroll/reports',
                'icon' => 'assessment',
                'permission' => 'view-reports',
                'order' => 8,
                'type' => 'menu',
            ],
            [
                'system_key' => 'hr.employees',
                'module_code' => 'hr',
                'title' => 'Employees',
                'route' => '/hr/employees',
                'icon' => 'groups',
                'permission' => 'view-employees',
                'order' => 2,
                'type' => 'menu',
            ],
            [
                'system_key' => 'payroll.employees',
                'module_code' => 'payroll',
                'title' => 'Employees',
                'route' => '/payroll/employees',
                'icon' => 'groups',
                'permission' => 'view-employees',
                'order' => 2,
                'type' => 'menu',
            ],
            [
                'system_key' => 'hr.scheduler',
                'module_code' => 'payroll',
                'title' => 'Scheduler',
                'route' => '/payroll/scheduler',
                'icon' => 'calendar_month',
                'permission' => 'view-calendars',
                'order' => 3,
                'type' => 'menu',
            ],
            [
                'system_key' => 'hr.timesheet',
                'module_code' => 'payroll',
                'title' => 'Timesheet',
                'route' => '/payroll/timesheet',
                'icon' => 'schedule',
                'permission' => 'view-timesheets',
                'order' => 4,
                'type' => 'menu',
            ],
            [
                'system_key' => 'hr.leaves',
                'module_code' => 'payroll',
                'title' => 'Leaves',
                'route' => '/payroll/leaves',
                'icon' => 'event_busy',
                'permission' => 'view-leave',
                'order' => 5,
                'type' => 'menu',
            ],
            [
                'system_key' => 'payroll.root',
                'module_code' => 'payroll',
                'title' => 'Payroll',
                'route' => '/payroll',
                'icon' => 'payments',
                'permission' => 'view-payroll',
                'order' => 6,
                'type' => 'menu',
            ],
            [
                'system_key' => 'payroll.settings',
                'module_code' => 'payroll',
                'title' => 'Settings',
                'route' => '/payroll/settings',
                'icon' => 'settings',
                'permission' => 'view-settings',
                'order' => 7,
                'type' => 'menu',
            ],
            [
                'system_key' => 'admin.settings',
                'module_code' => 'admin',
                'title' => 'Settings',
                'route' => '/admin/settings',
                'icon' => 'settings',
                'permission' => 'view-settings',
                'order' => 1,
                'type' => 'menu',
            ],
            [
                'system_key' => 'admin.pipelines',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Pipelines',
                'route' => '/admin/settings/pipelines',
                'icon' => 'account_tree',
                'permission' => 'view-pipeline-templates',
                'order' => 1,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.modules',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Modules',
                'route' => '/admin/settings/modules',
                'icon' => 'apps',
                'permission' => 'manage-modules',
                'order' => 2,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.database_backup',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Database Backup',
                'route' => '/admin/settings/database-backup',
                'icon' => 'fas fa-database',
                'permission' => 'view-database-backup',
                'order' => 3,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.menu',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Menu',
                'route' => '/admin/settings/menu',
                'icon' => 'fas fa-bars',
                'permission' => 'view-menu',
                'order' => 4,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.roles',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Roles',
                'route' => '/admin/settings/roles',
                'icon' => 'fas fa-user-shield',
                'permission' => 'view-roles',
                'order' => 5,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.organization',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Organization',
                'route' => '/admin/settings/organization',
                'icon' => 'fas fa-building',
                'permission' => 'view-organization',
                'order' => 6,
                'type' => 'submenu',
            ],
            [
                'system_key' => 'admin.users',
                'module_code' => 'admin',
                'parent_system_key' => 'admin.settings',
                'title' => 'Users',
                'route' => '/admin/settings/users',
                'icon' => 'fa-solid fa-users',
                'permission' => 'manager-users|reset-subordinate-passwords',
                'order' => 7,
                'type' => 'submenu',
            ],
        ];
    }
}
